language: cpp
os: linux
dist: focal
compiler: gcc
branches:
  only:
    - master

before_install: ./scripts/ci_dependencies.sh

jobs:
  include:
    - stage: build
      script: ./scripts/ci_debug_build.sh
      script: ./scripts/ci_release_build.sh
    - stage: build
      script: doxygen Doxyfile
      deploy:
        edge: true
        provider: pages
        strategy: git
        local_dir: docs
        token: $GH_REPO_TOKEN
        on:
          branch: master

stages:
  - build
  - documentation