language: cpp
os: linux
dist: focal
compiler: gcc
before_install:
        - sudo apt-get update
        - sudo apt-get -y install libeigen3-dev pybind11-dev scons python3-dev libbenchmark-dev
script: ./ci_build.sh