language: cpp
os: linux
dist: focal
compiler: gcc
before_install:
        - sudo apt-get update
        - sudo apt-get -y install libeigen3-dev pybind11-dev scons
jobs:
        include:
                - stage: build
                  script: bash build.sh
                - stage: test
                  script: ./Tests/build/Debug/Tests
                - stage: benchmark
                  script: ./Benchmarks/build/Release/Benchmarks
