language: cpp
os: linux
dist: focal
compiler: gcc
branches:
  only:
    - master

before_install: ./scripts/ci_dependencies.sh

jobs:
  include:
    - stage: build
      script: ./scripts/ci_build.sh
    - stage: documentation
      script: doxygen Doxyfile

deploy:
  strategy: git
  provider: pages
  cleanup: true
  local_dir: docs
  token: $GH_REPO_TOKEN
  on:
    branch: master
