language: cpp
os: linux
dist: focal
compiler: gcc
branches:
  only:
    - master

before_install: ./scripts/ci_dependencies.sh

jobs:
  include:
    - stage: build
      name: "Debug build"
      script: ./scripts/ci_debug_build.sh      
    - # continue in build
      name: "Release build"
      script: ./scripts/ci_release_build.sh
    - stage: documentation
      script: doxygen Doxyfile
      deploy:
        edge: true
        provider: pages
        strategy: git
        local_dir: docs
        token: $GH_REPO_TOKEN
        on:
          branch: master

stages:
  - build
  - documentation