Import('env')
Import('MLObjs')
penv = env.Clone()
# pybind11 include directory should be under this:
penv.Append(CXXFLAGS=['-isystem/usr/include/python3.6/'])
penv['SHLIBPREFIX'] = ''  # We need cppyml.so, not libPyML.so
cppyml = penv.SharedLibrary('cppyml', Glob('*.cpp') + MLObjs)
Return('cppyml')
