name: ML++
on: [push]
jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: ./scripts/ci_dependencies.sh ubuntu_required_packages_build.txt
      - name: Debug build
        run: ./scripts/ci_debug_build.sh
      - name: Release build
        if: github.ref == 'refs/heads/master'
        run: ./scripts/ci_release_build.sh      
      - name: Install documentation dependencies
        if: github.ref == 'refs/heads/master'
        run: ./scripts/ci_dependencies.sh ubuntu_required_packages_documentation.txt
      - name: Update documentation
        if: github.ref == 'refs/heads/master'
        run: |
            find .
            ./scripts/ci_documentation.sh
            git config --global user.name 'Roman Werpachowski'
            git config --global user.email 'romanwerpachowski@users.noreply.github.com'
            git commit -am "Auto-update documentation" || echo "No changes to commit"
            git pull --ff-only
            git push